### ISSUE TITLE
Contact Details

### ISSUE THREAD

**Issue by scottharvey** [simukappu/amazon-chime-sdk-rails#8]
Hi Shota,

I sent you an email using the email address in your Github profile.

If you didn't receive it can you email me at scott@scottharvey.co 

I would like to ask a few questions about this repository.

Feel free to delete this issue. 😃

**Comment by simukappu** [comment]
Hi @scottharvey, thank you for reaching to me.
Please write your questions in issues in this repository if you have any questions about this gem.
Thank you!

**Comment by scottharvey** [comment]
@simukappu The question was about hiring you for contract work, if you are interested let me know.
